### ISSUE TITLE
[feat] 1. 자바 기본문법-1

### ISSUE THREAD

**Issue by happine2s** [happine2s/Java_study#1]
## 📌  Practice

[dinfree: 자바 기본문법-1](https://dinfree.com/lecture/language/112_java_2.html)

## 📝  To-do

- [x] 자바 프로그램 구조
- [x] 변수와 메서드 실습
- [x] 연산자 실습
- [x] 자바 메모리 관리
